### ISSUE TITLE
BNN Compatibility with MYiR Zynq XC7Z020

### ISSUE THREAD

**Issue by kdpatino** [Xilinx/BNN-PYNQ#10]
Hello,

I have a MYiR Zynq XC7Z020 board with two ddr3 IC and I want to run the BNN over there. Unfortunately I
 just found a .bit file for the PYNQ board. Can this project be ported to others Zynq base boards? 

Thank you in advance.

Kevin

**Comment by maltanar** [comment]
Hardware (FPGA) compatibility is no problem since both chips are Z7020. Depending on the Linux build you have, the driver support may require a bit of manual work though. 

You could try and see if your board can run the PYNQ Linux release (here's someone who did it for the ZedBoard: http://zedboard.org/content/general-guidelince-install-linux-zed-board-and-how-install-pynq-linux-zedboard).
