### ISSUE TITLE
Creating a new network having extra layers

### ISSUE THREAD

**Issue by Shruthi-Bhaasini** [Xilinx/BNN-PYNQ#106]
In order to create a new network having extra layers, the PE and SIMD counts for each layer is required to be provided in the script [NETWORK]-gen-weights-[WxAy].py . How do we decide the values of these parameters?

**Comment by giuliogamba** [comment]
Hi, 
if you define properly the network topology (for example from line 43 to 47 in this [file](https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/src/training/cifar10-gen-weights-W1A1.py)), the finnthesizer used when exporting the network parameters calculates the number of operations per layer and estimates the latency per each layer (Ext Latency in the [config.h](https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/src/network/cnvW1A1/hw/config.h)). 
You should select the parallelism values (SIMD and PE) in order to have approximately the same estimated latency for each layer in order to have a balanced dataflow.
