### ISSUE TITLE
Warning: Cannot find design file

### ISSUE THREAD

**Issue by jpan127** [Xilinx/BNN-PYNQ#6]
Hi I am trying to setup this package and I am running into a few issues.

I cloned the repository, set the XILINX_BNN_ROOT variable, launched the hw shell script for both cnv-pynq and lfc-pynq but I get this error.

![error2](https://cloud.githubusercontent.com/assets/19752007/26281860/77be8d62-3db8-11e7-8c67-8b177981bc83.PNG)

Another issue I have is I'm not clear on the quick start instructions for the Pynq board.  It is asking to copy the include folder from Windows  **to the** Pynq board correct?  I was wondering if there is an easy way to copy the folder since there is over 200 files, and Jupyter does not let me import folders, only files.

Thanks,
Jonathan

**Comment by giuliogamba** [comment]
Hi Jonathan, 

you can access and move data in PYNQ using Samba as described here (section "Accessing files on the board"): 
https://pynq.readthedocs.io/en/latest/1_getting_started.html#using-pynq

About your first issue, the flow has been tested on Unix systems. Can you provide more information about the flow you are trying to use? Anyway, at a first look it seems that you should change the XILINX_BNN_ROOT path using slash "/" instead of backslash "\" .

**Comment by jpan127** [comment]
Hi giuliogamba,

I am using Windows 10 64 bit, Vivado 2016.4 design suite, GCC 6.2.0.  I changed my environment variable to forward slashes instead of back slashes and that got rid of the first error.  However I am getting a second error with compilation.

![e1](https://cloud.githubusercontent.com/assets/19752007/26387195/65a48e66-4000-11e7-971a-958707c1397d.PNG)
![e2](https://cloud.githubusercontent.com/assets/19752007/26387196/65b3c098-4000-11e7-83d4-ea6997ca762f.PNG)
