### ISSUE TITLE
How to set the PE, SIMD and Folded

### ISSUE THREAD

**Issue by hshintaro575** [Xilinx/BNN-PYNQ#78]
Hi, everyone.

Now, I have been developing CNN of unique design.
My designed architecture is:
  The input image is 60 x 60 x 1 (x, y, c).
  The output is 3 classes.
  The hidden layer is CNN generally (cnv -> cnv -> dense -> out).

I find two hard-codings in code that is gen-weights.py of the training phase and top.cpp of the generating bitstream phase.

The problem 1 [gen-weights.py]:
After training by the theano, I divided the weights.
However, I don't know how to divide.

e.g.
peCounts = [16, 32, 16, 16, 16, 16, 1, 1, 4]
simdCounts = [ 3, 32, 32, 32, 32, 32, 4, 8, 1]

I estimate the Ext Latency from the processing number of each layer,
and adjusted the Ext Latency to be the same delay number in all layers.

Is there a quantitative calculation method the above?
Although I read the FINN paper, not sure.

The problem 2 [top.cpp]:
After dividing the weights, I generated a bitstream.
However, I occur many of the warnings.

e.g.
  WARNING: Hls::stream 'DoCompute.inter0_2' is read while empty, which may result in RTL simulation hanging.
  ...

Although I assume that I mistake the size of StreamingDataWidth,
I don't know how to set the size number.

I changed the source code of  main_python, top.cpp, and foldedmv-offload which may be related.
e.g. loading image function, data forwarding function.
However, I didn't solve.

Maybe, should the number of Streaming size be divisible by 64?

Thanks for your warm help in advance.

e.g.
Mem2Stream_Batch<64, inBits / 8>(in, inter0, numReps);
StreamingDataWidthConverter_Batch<64, 192, (32 * 32 * 1 * 8) / 64>(inter0, inter0_1, numReps);
StreamingDataWidthConverter_Batch<192, 24, (32 * 32 * 1 * 8) / 192>(inter0_1, inter0_2, numReps);

**Comment by giuliogamba** [comment]
Hi, 
here some pointers for your question:
1. You should select the values of SIMD and PE according to the compute of each layer. If you properly define the topology (using the appropriate values of feature maps channels/dimensions and layers as in [this](https://github.com/Xilinx/BNN-PYNQ/blob/2b502ddb57aa4010fb34e4e36c7e1fb95902684c/bnn/src/training/cifar10-gen-weights-W1A1.py) example), the tool will calculate the compute of each layer and given the selected parallelism (SIMD and PE) will estimate the latency. 
2. You should select the size of the streams according to the input/output width for each channel. The problem is the input, since `60*60*1` makes 3600 bits/image, which is not multiple of 64 (width of the AXI4 interface). I suggest to pad the input image on the host to the first multiple of 64 (3648 bits) then read the padded size, downscale the stream with a datawidth converter (to a width of 48) and then use the `StreamLimiter` function to drop the padding. 

Hope this helps.
